<?php

/**
 * This documentation group collects source code files belonging to Ask.
 *
 * @defgroup Ask Ask
 */

/**
 * Tests part of the Ask extension.
 *
 * @defgroup AskTests AskTest
 * @ingroup Ask
 * @ingroup Test
 */

if ( defined( 'Ask_VERSION' ) ) {
	// Do not initialize more then once.
	return;
}

define( 'Ask_VERSION', '1.0 RC' );

// Attempt to include the dependencies if one has not been loaded yet.
// This is the path to the autoloader generated by composer in case of a composer install.
if ( ( !defined( 'DataValues_VERSION' ) || !defined( 'Serialization_VERSION' ) ) && is_readable( __DIR__ . '/vendor/autoload.php' ) ) {
	include_once( __DIR__ . '/vendor/autoload.php' );
}

// Attempt to include the DataValues lib if that hasn't been done yet.
// This is the path the DataValues entry point will be at when loaded as MediaWiki extension.
if ( !defined( 'DataValues_VERSION' ) && is_readable( __DIR__ . '/../DataValues/DataValues.php' ) ) {
	include_once( __DIR__ . '/../DataValues/DataValues.php' );
}

// Attempt to include the Serialization lib if that hasn't been done yet.
// This is the path the Serialization entry point will be at when loaded as MediaWiki extension.
if ( !defined( 'Serialization_VERSION' ) && is_readable( __DIR__ . '/../Serialization/Serialization.php' ) ) {
	include_once( __DIR__ . '/../Serialization/Serialization.php' );
}

// Only initialize the extension when all dependencies are present.
if ( !defined( 'DataValues_VERSION' ) ) {
	throw new Exception( 'You need to have the DataValues library loaded in order to use Ask' );
}

// Only initialize the extension when all dependencies are present.
if ( !defined( 'Serialization_VERSION' ) ) {
	throw new Exception( 'You need to have the Serialization library loaded in order to use Ask' );
}

// @codeCoverageIgnoreStart
spl_autoload_register( function ( $className ) {
	$className = ltrim( $className, '\\' );
	$fileName = '';
	$namespace = '';

	if ( $lastNsPos = strripos( $className, '\\') ) {
		$namespace = substr( $className, 0, $lastNsPos );
		$className = substr( $className, $lastNsPos + 1 );
		$fileName  = str_replace( '\\', '/', $namespace ) . '/';
	}

	$fileName .= str_replace( '_', '/', $className ) . '.php';

	$namespaceSegments = explode( '\\', $namespace );

	if ( $namespaceSegments[0] === 'Ask' ) {
		if ( count( $namespaceSegments ) === 1 || $namespaceSegments[1] !== 'Tests' ) {
			require_once __DIR__ . '/src/' . $fileName;
		}
	}
} );

if ( defined( 'MEDIAWIKI' ) ) {
	call_user_func( function() {
		require_once __DIR__ . '/Ask.mw.php';
	} );
}
// @codeCoverageIgnoreEnd
